### ISSUE TITLE
New Tron style looks weird

### ISSUE THREAD

**Issue by rwrx** [mapzen/android#206]
I have updated Mapzen Android SDK to newest master and wanted to try new Tron style, but when I run sample app and switched to Tron style, it looks weird. I am attaching images.

![tron1](https://cloud.githubusercontent.com/assets/2378743/19475261/80582cd6-9533-11e6-8b17-730045315c44.png)
![tron2](https://cloud.githubusercontent.com/assets/2378743/19475262/80596a42-9533-11e6-91ae-e7d2831e01bd.png)
![tron3](https://cloud.githubusercontent.com/assets/2378743/19475263/805e48f0-9533-11e6-8c3c-c1de781ff45a.png)

**Comment by ecgreb** [comment]
I am seeing the same issue since updating the tron stylesheet for our vector tiles 1.0 release. We are currently investigating.

**Comment by ecgreb** [comment]
Could be related to scene imports. Tracking here:

https://github.com/tangrams/tangram-es/issues/1021

**Comment by ecgreb** [comment]
This issue is coming from an incompatibility between `AssetManager` and the style sheet imports. More information in #214 

The new version of Tron needs to be removed from the SDK until a permanent fix can be implemented.

**Comment by rwrx** [comment]
Thank you for information.

**Comment by ecgreb** [comment]
Stylesheet import issues have now been resolved in Tangram ES (link?) so the new Tron style should now be compatible with the current version of the Android SDK.

The question still remains whether this should be a bundled stylesheet distributed with the SDK (probably not) or whether it should only be available when implemented as a custom stylesheet (either locally or via remote URL).

**Comment by rwrx** [comment]
Why shouldn't be Tron distributed with SDK as other Mapzen styles are distributed in SDK already? I don't mind it, I am just curious.

**Comment by rwrx** [comment]
I have tried Tron 2.0 with current version of Mapzen Android SDK and still it looks the same as in screenshots I have sent previously.

**Comment by ecgreb** [comment]
When using the new tron stylesheet, submodules must be initialized recursively since `tron-style` includes its own submodule `blocks`.

https://github.com/mapzen/android/pull/318 updates the custom stylesheet demo to use the latest version of tron and documents the requirement to recursively init and update submodules.

We still won't be including tron as a bundled stylesheet in the SDK mainly due to the size of the stylesheet once initialized it would add roughly 4.2M to the size of the AAR.

```
Wed Mar 01 05:17 PM #2135 /usr/local/code/mapzen-android-sdk [new-tron] 
$ du -sh samples/mapzen-android-sdk-sample/src/main/assets/styles/tron-style/
4.2M    samples/mapzen-android-sdk-sample/src/main/assets/styles/tron-style/
```

**Comment by rwrx** [comment]
I have pulled newest version on master branch but unfortunately on my Nexus 5 and 5X I am still having this issue :(.
